openapi: 3.0.3
info:
  contact:
    name: murithiedwing
paths:
  /hello:
    x-exegesis-controller: helloController
    get:
      x-exegesis-operationId: sayHello
      responses:
        "200":
          description: Successful
  /:
    x-exegesis-controller: serverRoot
    get:
      x-exegesis-operationId: getServerRoot
      responses:
        "200":
          description: Successful
  /api.html:
    x-exegesis-controller: rootApi
    get:
      x-exegesis-operationId: seeThisDoc
      responses:
        "200":
          description: Successful
          content:
            text/yaml:
              schema:
                type: string