import type { ExegesisPlugin, ExegesisPluginContext } from "exegesis";
import process from "node:process";
import { CRS84 } from "./projection.ts";
import type { Bbox } from "./types.d.ts";
import { bbox2polygon } from "./bbox2polygon.ts"
import {reprojectAndFlip} from "./projection.ts"
import type { IncomingMessage } from "node:http";
const { NODE_ENV = "development" } = process.env;

/**
 * @description creates an object at context root called ectx
 */
export function makeExtraContext(): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-make-extra-context" },
    makeExegesisPlugin: () => ({
      preRouting: () => {
        // console.log(req)
      },
      postRouting: (ctx: ExegesisPluginContext) => {
        ctx["ectx"] = Object.assign({});
      },
    }),
  };
}

export function setServerSuffix(suffix: string): ExegesisPlugin {
  return {
    info: {
      name: "set-server-suffix",
    },
    makeExegesisPlugin: () => {
      return {
        postRouting: (ctx: ExegesisPluginContext) => {
          const url = new URL(`http://${ctx.req.headers.host}/${suffix}`);
          if (NODE_ENV === "production") url.protocol = "https";
          ctx.api.serverObject = {
            url: url.toString(),
            description: `${NODE_ENV} server. Autogenerated depending on host`,
          };
          ctx["ectx"]["server"] = url.toString();
        },
      };
    },
  };
}

/**
 *
 * @param collectionIds A list of valid dataset ids
 */
export function collectionIdPlugin(
  datasets: Array<{ id: string }>
): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-collectionId-validator" },
    makeExegesisPlugin: () => {
      return {
        postSecurity: async (ctx: ExegesisPluginContext) => {
          const params = await ctx.getParams();
          if (!("collectionId" in params.path)) return;
          const dataset = datasets.find(
            (d) => d.id === params.path.collectionId
          );
          if (!dataset) throw ctx.makeError(404, "no such dataset/collection");
          ctx["ectx"].dataset = dataset;
        },
      };
    },
  };
}

/**
 * @description validates crs query param uris before controller
 */
export function crsParamPlugin(): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-crs-validator" },
    makeExegesisPlugin: () => {
      return {
        postSecurity: async (ctx: ExegesisPluginContext) => {
          const params = await ctx.getParams();
          if (!("crs" in params.query)) return;
          const dataset: { id: string; crs: string[] } = ctx["ectx"].dataset;
          params.query.crs = params.query.crs || CRS84;
          const value = dataset.crs.find((c) => c === params.query.crs);
          if (!value) {
            throw ctx.makeValidationError(
              `invalid crs uri/id. Review doc at /collections for valid values`,
              { in: "query", name: "crs", docPath: ctx.api.pathItemPtr }
            );
          }
          ctx["ectx"]["crs"] = value;
          ctx.res.set("content-crs", `<${value}>`);
        },
      };
    },
  };
}

/**
 *@param limit the default limit value if param.query.limit is not an integer
 */
export function paginationPlugin(limit: number): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-pagination" },
    makeExegesisPlugin: () => ({
      postSecurity: async (ctx: ExegesisPluginContext) => {
        const params = await ctx.getParams();
        // Limit
        ctx["ectx"]["limit"] = Number.isInteger(params.query.limit)
          ? params.query.limit
          : limit;
        ctx["ectx"]["offset"] = Number.isInteger(params.query.offset)
          ? params.query.offset
          : 0;
      },
    }),
  };
}

/**
 * @description parses values from the z query parameter
 */
export function datetimePlugin(): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-datetime" },
    makeExegesisPlugin: () => ({
      preRouting({ req }: { req: IncomingMessage }) {
        // req.url = encodeURIComponent(req.);
        console.log(req.url);
      },

      postSecurity: async (ctx: ExegesisPluginContext) => {
        const params = await ctx.getParams();
        let datetime: string | undefined = params.query?.datetime;
        if (!datetime) return;
        datetime = datetime.replace(" ", "+");
        let max: string | undefined;
        let min: string | undefined;
        let values: string[] | undefined;
        if (!datetime.includes("/")) values = datetime.split(",");
        else {
          if (datetime.startsWith("../")) {
            [, max] = datetime.split("../");
          } else if (datetime.endsWith("/..")) {
            [min] = datetime.split("/..");
          } else [min, max] = datetime.split("/");
        }
        try {
          ctx["ectx"]["datetime"] = {
            max: (max && new Date(max).toISOString()) || undefined,
            min: (min && new Date(min).toISOString()) || undefined,
            values: values
              ? values.map((str) => new Date(str).toISOString())
              : undefined,
          };
        } catch (error) {
          console.log(error);
          throw ctx.makeValidationError(`Invalid date[/]time value`, {
            in: "query",
            name: "datetime",
            docPath: ctx.api.pathItemPtr,
          });
        }
      },
    }),
  };
}

/**
 * @requires running before the bboxPlugin which mutates the bbox value
 */
export function elevationPlugin(): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-elevation(z)-parser" },
    makeExegesisPlugin: () => ({
      preRouting: () => {
        // const params = querystring.parse(req.url?.split("?")[1]!);
        // if (params.bbox) {
        //   params.bbox = (decodeURIComponent(params.bbox))
        //   console.log(params.bbox)
        // }
      },
      postSecurity: async (ctx: ExegesisPluginContext) => {
        const params = await ctx.getParams();
        // z parameter takes precedence over height values in bbox
        let z: string | undefined = params.query.z;
        const bbox: Bbox | undefined = params.query.bbox;
        if (!z && bbox && bbox.length === 6) z = [bbox[2], bbox[5]].join("/");
        if (!z) return;

        /**
         * single value z=850
         * range z=10/100
         * list z=value1,value2,valueN
         * sequence z=Rn/minHeight/heightInterval
         * R20/100/50
         */
        let max: number | undefined;
        let min: number | undefined;
        let values: number[] | undefined;

        if (z.startsWith("R")) {
          values = [];
          //An=A1+(n-1)d
          const [intervals, a0, d] = z.substring(1).split("/");
          for (let n = 1; n <= parseFloat(intervals); n++) {
            const aN = parseFloat(a0) + (n - 1) * parseFloat(d);
            values.push(aN);
          }
        } else {
          if (z.includes("/"))
            [min, max] = z.split("/").map((p) => parseFloat(p));
          else values = z.split(",").map((p) => parseFloat(p));
        }
        ctx["ectx"]["z"] = {
          min,
          max,
          values,
        };
      },
    }),
  };
}

/**
 *
 * @description if on features, use a plugin to validate bbox-crs
 * @param crsField The field from which to get the CRS info
 * Run before parsing z param because it overwrites the z object
 */
export function bboxPlugin(crsField: string = "crs"): ExegesisPlugin {
  return {
    info: { name: "exegesis-plugin-bboxcrs-validator" },
    makeExegesisPlugin: () => ({
      postSecurity: async (ctx: ExegesisPluginContext) => {
        const params = await ctx.getParams();
        if (!params.query.bbox) return;

        const crs: string = ctx["ectx"][crsField];
        const storageCrs: string = ctx["ectx"]["dataset"]["storageCrs"];
        const bbox: Bbox = params.query.bbox;

        let xyComponent: [number, number, number, number];
        if (bbox.length === 4) xyComponent = bbox;
        else {
          xyComponent = [bbox[0], bbox[1], bbox[3], bbox[4]];
          ctx["ectx"]["z"] = { min: bbox[2], max: bbox[5] };
        }
        const transformed = reprojectAndFlip(
          crs,
          storageCrs
        )({
          type: "Feature",
          geometry: bbox2polygon(xyComponent),
          properties: {},
        }).geometry;
        ctx["ectx"]["bbox"] = transformed;
        // if (bbox.length === 4) {
        //   params.query.bbox = crs_.flipCoords
        //     ? [bbox[1], bbox[0], bbox[3], bbox[2]]
        //     : [bbox[0], bbox[1], bbox[2], bbox[3]];
        // } else {
        //   params.query.bbox = crs_.flipCoords
        //     ? [bbox[1], bbox[0], bbox[4], bbox[3]]
        //     : [bbox[0], bbox[1], bbox[3], bbox[4]];
        // }
      },
    }),
  };
}
