@lAN=http://localhost:3000/features

### Root
{{lAN}}/?f=html

### conformance
{{lAN}}/conformance

###
GET {{lAN}}/api?f=html

### API html
GET {{lAN}}/api.html HTTP/1.1


###
GET {{lAN}}/collections

###
GET {{lAN}}/collections/mountains

####
GET {{lAN}}/collections/world-mountains/items?f=geojson&crs=http://www.opengis.net/def/crs/EPSG/0/4326

###
GET {{lAN}}/collections/world-mountains/items/Mount Kenya?crs=http://www.opengis.net/def/crs/EPSG/0/4326