datasets:
  - name: world-mountains
    crs:
      - *OGC:CRS84
      - *OGC:CRS84h
    attribution:
      - rel: author
        href: mailto:jason@waldrip.net
        title: Email Jason Waldrip
      - rel: original
        href: https://github.com/open-peaks/data
        title: Github Repo
        type: text/html
    storageCrs: *OGC:CRS84
    title: World Mountains and their Heights
servers:
  - url: https://server-template.vercel.app/features
    description: Production Server